export type InstitutionCampusMapping = {
  institutionId: number;
  institutionName: string;
  campusId: number;
  campusName: string;
  fullCampusName: string;
};

export const INSTITUTION_CAMPUS_MAPPINGS: readonly InstitutionCampusMapping[] = [
  { institutionId: 2, institutionName: "LH토지주택대학교", campusId: 1, campusName: "본교", fullCampusName: "LH토지주택대학교" },
  { institutionId: 1, institutionName: "건국대학교", campusId: 18, campusName: "서울캠퍼스", fullCampusName: "건국대학교 서울캠퍼스" },
  { institutionId: 1, institutionName: "건국대학교", campusId: 17, campusName: "GLOCAL캠퍼스", fullCampusName: "건국대학교 GLOCAL캠퍼스" },
  { institutionId: 3, institutionName: "가야대학교", campusId: 2, campusName: "본교", fullCampusName: "가야대학교" },
  { institutionId: 4, institutionName: "가천대학교", campusId: 3, campusName: "글로벌캠퍼스", fullCampusName: "가천대학교 글로벌캠퍼스" },
  { institutionId: 4, institutionName: "가천대학교", campusId: 4, campusName: "메디컬캠퍼스", fullCampusName: "가천대학교 메디컬캠퍼스" },
  { institutionId: 5, institutionName: "가톨릭관동대학교", campusId: 5, campusName: "본교", fullCampusName: "가톨릭관동대학교" },
  { institutionId: 6, institutionName: "가톨릭꽃동네대학교", campusId: 6, campusName: "본교", fullCampusName: "가톨릭꽃동네대학교" },
  { institutionId: 7, institutionName: "가톨릭대학교", campusId: 8, campusName: "성심교정", fullCampusName: "가톨릭대학교 성심교정" },
  { institutionId: 7, institutionName: "가톨릭대학교", campusId: 9, campusName: "성의교정", fullCampusName: "가톨릭대학교 성의교정" },
  { institutionId: 7, institutionName: "가톨릭대학교", campusId: 7, campusName: "성신교정", fullCampusName: "가톨릭대학교 성신교정" },
  { institutionId: 8, institutionName: "감리교신학대학교", campusId: 10, campusName: "본교", fullCampusName: "감리교신학대학교" },
  { institutionId: 9, institutionName: "강남대학교", campusId: 11, campusName: "본교", fullCampusName: "강남대학교" },
  { institutionId: 10, institutionName: "강서대학교", campusId: 12, campusName: "본교", fullCampusName: "강서대학교" },
  { institutionId: 11, institutionName: "강원대학교", campusId: 16, campusName: "춘천캠퍼스", fullCampusName: "강원대학교 춘천캠퍼스" },
  { institutionId: 11, institutionName: "강원대학교", campusId: 14, campusName: "삼척캠퍼스", fullCampusName: "강원대학교 삼척캠퍼스" },
  { institutionId: 11, institutionName: "강원대학교", campusId: 13, campusName: "강릉캠퍼스", fullCampusName: "강원대학교 강릉캠퍼스" },
  { institutionId: 11, institutionName: "강원대학교", campusId: 15, campusName: "원주캠퍼스", fullCampusName: "강원대학교 원주캠퍼스" },
  { institutionId: 12, institutionName: "건양대학교", campusId: 20, campusName: "창의융합캠퍼스", fullCampusName: "건양대학교 창의융합캠퍼스" },
  { institutionId: 12, institutionName: "건양대학교", campusId: 19, campusName: "메디컬캠퍼스", fullCampusName: "건양대학교 메디컬캠퍼스" },
  { institutionId: 13, institutionName: "건양사이버대학교", campusId: 21, campusName: "본교", fullCampusName: "건양사이버대학교" },
  { institutionId: 14, institutionName: "경기대학교", campusId: 23, campusName: "수원캠퍼스", fullCampusName: "경기대학교 수원캠퍼스" },
  { institutionId: 14, institutionName: "경기대학교", campusId: 22, campusName: "서울캠퍼스", fullCampusName: "경기대학교 서울캠퍼스" },
  { institutionId: 15, institutionName: "경남대학교", campusId: 24, campusName: "본교", fullCampusName: "경남대학교" },
  { institutionId: 16, institutionName: "경동대학교", campusId: 25, campusName: "글로벌캠퍼스", fullCampusName: "경동대학교 글로벌캠퍼스" },
  { institutionId: 16, institutionName: "경동대학교", campusId: 27, campusName: "메트로폴캠퍼스", fullCampusName: "경동대학교 메트로폴캠퍼스" },
  { institutionId: 16, institutionName: "경동대학교", campusId: 26, campusName: "메디컬캠퍼스", fullCampusName: "경동대학교 메디컬캠퍼스" },
  { institutionId: 17, institutionName: "경북대학교", campusId: 28, campusName: "대구캠퍼스", fullCampusName: "경북대학교 대구캠퍼스" },
  { institutionId: 17, institutionName: "경북대학교", campusId: 29, campusName: "동인캠퍼스", fullCampusName: "경북대학교 동인캠퍼스" },
  { institutionId: 17, institutionName: "경북대학교", campusId: 30, campusName: "상주캠퍼스", fullCampusName: "경북대학교 상주캠퍼스" },
  { institutionId: 18, institutionName: "경상국립대학교", campusId: 31, campusName: "가좌캠퍼스", fullCampusName: "경상국립대학교 가좌캠퍼스" },
  { institutionId: 18, institutionName: "경상국립대학교", campusId: 32, campusName: "칠암캠퍼스", fullCampusName: "경상국립대학교 칠암캠퍼스" },
  { institutionId: 18, institutionName: "경상국립대학교", campusId: 33, campusName: "통영캠퍼스", fullCampusName: "경상국립대학교 통영캠퍼스" },
  { institutionId: 19, institutionName: "경성대학교", campusId: 34, campusName: "본교", fullCampusName: "경성대학교" },
  { institutionId: 20, institutionName: "경운대학교", campusId: 35, campusName: "본교", fullCampusName: "경운대학교" },
  { institutionId: 21, institutionName: "경인교육대학교", campusId: 37, campusName: "인천캠퍼스", fullCampusName: "경인교육대학교 인천캠퍼스" },
  { institutionId: 21, institutionName: "경인교육대학교", campusId: 36, campusName: "경기캠퍼스", fullCampusName: "경인교육대학교 경기캠퍼스" },
  { institutionId: 22, institutionName: "경일대학교", campusId: 38, campusName: "본교", fullCampusName: "경일대학교" },
  { institutionId: 23, institutionName: "경희대학교", campusId: 40, campusName: "서울캠퍼스", fullCampusName: "경희대학교 서울캠퍼스" },
  { institutionId: 23, institutionName: "경희대학교", campusId: 39, campusName: "국제캠퍼스", fullCampusName: "경희대학교 국제캠퍼스" },
  { institutionId: 24, institutionName: "경희사이버대학교", campusId: 41, campusName: "본교", fullCampusName: "경희사이버대학교" },
  { institutionId: 25, institutionName: "계명대학교", campusId: 43, campusName: "성서캠퍼스", fullCampusName: "계명대학교 성서캠퍼스" },
  { institutionId: 25, institutionName: "계명대학교", campusId: 42, campusName: "대명캠퍼스", fullCampusName: "계명대학교 대명캠퍼스" },
  { institutionId: 26, institutionName: "고려대학교", campusId: 44, campusName: "서울캠퍼스", fullCampusName: "고려대학교 서울캠퍼스" },
  { institutionId: 26, institutionName: "고려대학교", campusId: 45, campusName: "세종캠퍼스", fullCampusName: "고려대학교 세종캠퍼스" },
  { institutionId: 27, institutionName: "고려사이버대학교", campusId: 46, campusName: "본교", fullCampusName: "고려사이버대학교" },
  { institutionId: 28, institutionName: "고신대학교", campusId: 48, campusName: "영도캠퍼스", fullCampusName: "고신대학교 영도캠퍼스" },
  { institutionId: 28, institutionName: "고신대학교", campusId: 47, campusName: "송도캠퍼스", fullCampusName: "고신대학교 송도캠퍼스" },
  { institutionId: 29, institutionName: "공주교육대학교", campusId: 49, campusName: "본교", fullCampusName: "공주교육대학교" },
  { institutionId: 30, institutionName: "광신대학교", campusId: 50, campusName: "본교", fullCampusName: "광신대학교" },
  { institutionId: 31, institutionName: "광운대학교", campusId: 51, campusName: "본교", fullCampusName: "광운대학교" },
  { institutionId: 32, institutionName: "광주가톨릭대학교", campusId: 52, campusName: "본교", fullCampusName: "광주가톨릭대학교" },
  { institutionId: 33, institutionName: "광주과학기술원", campusId: 53, campusName: "본교", fullCampusName: "광주과학기술원" },
  { institutionId: 34, institutionName: "광주교육대학교", campusId: 54, campusName: "본교", fullCampusName: "광주교육대학교" },
  { institutionId: 35, institutionName: "광주대학교", campusId: 55, campusName: "본교", fullCampusName: "광주대학교" },
  { institutionId: 36, institutionName: "광주여자대학교", campusId: 56, campusName: "본교", fullCampusName: "광주여자대학교" },
  { institutionId: 37, institutionName: "국립경국대학교", campusId: 57, campusName: "안동캠퍼스", fullCampusName: "국립경국대학교 안동캠퍼스" },
  { institutionId: 37, institutionName: "국립경국대학교", campusId: 58, campusName: "예천캠퍼스", fullCampusName: "국립경국대학교 예천캠퍼스" },
  { institutionId: 38, institutionName: "국립공주대학교", campusId: 59, campusName: "신관캠퍼스", fullCampusName: "국립공주대학교 신관캠퍼스" },
  { institutionId: 38, institutionName: "국립공주대학교", campusId: 61, campusName: "천안캠퍼스", fullCampusName: "국립공주대학교 천안캠퍼스" },
  { institutionId: 38, institutionName: "국립공주대학교", campusId: 60, campusName: "예산캠퍼스", fullCampusName: "국립공주대학교 예산캠퍼스" },
  { institutionId: 39, institutionName: "국립군산대학교", campusId: 62, campusName: "본교", fullCampusName: "국립군산대학교" },
  { institutionId: 40, institutionName: "국립금오공과대학교", campusId: 63, campusName: "본교", fullCampusName: "국립금오공과대학교" },
  { institutionId: 41, institutionName: "국립목포대학교", campusId: 65, campusName: "도림캠퍼스", fullCampusName: "국립목포대학교 도림캠퍼스" },
  { institutionId: 41, institutionName: "국립목포대학교", campusId: 64, campusName: "담양캠퍼스", fullCampusName: "국립목포대학교 담양캠퍼스" },
  { institutionId: 42, institutionName: "국립목포해양대학교", campusId: 66, campusName: "본교", fullCampusName: "국립목포해양대학교" },
  { institutionId: 43, institutionName: "국립부경대학교", campusId: 67, campusName: "본교", fullCampusName: "국립부경대학교" },
  { institutionId: 44, institutionName: "국립순천대학교", campusId: 68, campusName: "본교", fullCampusName: "국립순천대학교" },
  { institutionId: 45, institutionName: "국립창원대학교", campusId: 71, campusName: "창원캠퍼스", fullCampusName: "국립창원대학교 창원캠퍼스" },
  { institutionId: 45, institutionName: "국립창원대학교", campusId: 69, campusName: "거창캠퍼스", fullCampusName: "국립창원대학교 거창캠퍼스" },
  { institutionId: 45, institutionName: "국립창원대학교", campusId: 70, campusName: "남해캠퍼스", fullCampusName: "국립창원대학교 남해캠퍼스" },
  { institutionId: 46, institutionName: "국립한국교통대학교", campusId: 74, campusName: "충주캠퍼스", fullCampusName: "국립한국교통대학교 충주캠퍼스" },
  { institutionId: 46, institutionName: "국립한국교통대학교", campusId: 73, campusName: "증평캠퍼스", fullCampusName: "국립한국교통대학교 증평캠퍼스" },
  { institutionId: 46, institutionName: "국립한국교통대학교", campusId: 72, campusName: "의왕캠퍼스", fullCampusName: "국립한국교통대학교 의왕캠퍼스" },
  { institutionId: 47, institutionName: "국립한국해양대학교", campusId: 75, campusName: "본교", fullCampusName: "국립한국해양대학교" },
  { institutionId: 48, institutionName: "국립한밭대학교", campusId: 76, campusName: "본교", fullCampusName: "국립한밭대학교" },
  { institutionId: 49, institutionName: "국민대학교", campusId: 77, campusName: "본교", fullCampusName: "국민대학교" },
  { institutionId: 50, institutionName: "국제사이버대학교", campusId: 78, campusName: "본교", fullCampusName: "국제사이버대학교" },
  { institutionId: 51, institutionName: "극동대학교", campusId: 79, campusName: "본교", fullCampusName: "극동대학교" },
  { institutionId: 52, institutionName: "글로벌사이버대학교", campusId: 80, campusName: "본교", fullCampusName: "글로벌사이버대학교" },
  { institutionId: 53, institutionName: "금강대학교", campusId: 81, campusName: "본교", fullCampusName: "금강대학교" },
  { institutionId: 54, institutionName: "김천대학교", campusId: 82, campusName: "본교", fullCampusName: "김천대학교" },
  { institutionId: 55, institutionName: "나사렛대학교", campusId: 83, campusName: "본교", fullCampusName: "나사렛대학교" },
  { institutionId: 56, institutionName: "남부대학교", campusId: 84, campusName: "본교", fullCampusName: "남부대학교" },
  { institutionId: 57, institutionName: "남서울대학교", campusId: 85, campusName: "본교", fullCampusName: "남서울대학교" },
  { institutionId: 58, institutionName: "단국대학교", campusId: 86, campusName: "죽전캠퍼스", fullCampusName: "단국대학교 죽전캠퍼스" },
  { institutionId: 58, institutionName: "단국대학교", campusId: 87, campusName: "천안캠퍼스", fullCampusName: "단국대학교 천안캠퍼스" },
  { institutionId: 59, institutionName: "대구가톨릭대학교", campusId: 90, campusName: "효성캠퍼스", fullCampusName: "대구가톨릭대학교 효성캠퍼스" },
  { institutionId: 59, institutionName: "대구가톨릭대학교", campusId: 88, campusName: "루가캠퍼스", fullCampusName: "대구가톨릭대학교 루가캠퍼스" },
  { institutionId: 59, institutionName: "대구가톨릭대학교", campusId: 89, campusName: "유스티노캠퍼스", fullCampusName: "대구가톨릭대학교 유스티노캠퍼스" },
  { institutionId: 60, institutionName: "대구경북과학기술원", campusId: 91, campusName: "본교", fullCampusName: "대구경북과학기술원" },
  { institutionId: 61, institutionName: "대구교육대학교", campusId: 92, campusName: "본교", fullCampusName: "대구교육대학교" },
  { institutionId: 62, institutionName: "대구대학교", campusId: 93, campusName: "경산캠퍼스", fullCampusName: "대구대학교 경산캠퍼스" },
  { institutionId: 62, institutionName: "대구대학교", campusId: 94, campusName: "대명동캠퍼스", fullCampusName: "대구대학교 대명동캠퍼스" },
  { institutionId: 63, institutionName: "대구사이버대학교", campusId: 95, campusName: "본교", fullCampusName: "대구사이버대학교" },
  { institutionId: 64, institutionName: "대구예술대학교", campusId: 96, campusName: "본교", fullCampusName: "대구예술대학교" },
  { institutionId: 65, institutionName: "대구한의대학교", campusId: 97, campusName: "본교", fullCampusName: "대구한의대학교" },
  { institutionId: 66, institutionName: "대신대학교", campusId: 98, campusName: "본교", fullCampusName: "대신대학교" },
  { institutionId: 67, institutionName: "대전가톨릭대학교", campusId: 99, campusName: "본교", fullCampusName: "대전가톨릭대학교" },
  { institutionId: 68, institutionName: "대전대학교", campusId: 100, campusName: "본교", fullCampusName: "대전대학교" },
  { institutionId: 69, institutionName: "대전신학대학교", campusId: 101, campusName: "본교", fullCampusName: "대전신학대학교" },
  { institutionId: 70, institutionName: "대진대학교", campusId: 102, campusName: "본교", fullCampusName: "대진대학교" },
  { institutionId: 71, institutionName: "덕성여자대학교", campusId: 103, campusName: "본교", fullCampusName: "덕성여자대학교" },
  { institutionId: 72, institutionName: "동국대학교", campusId: 106, campusName: "서울캠퍼스", fullCampusName: "동국대학교 서울캠퍼스" },
  { institutionId: 72, institutionName: "동국대학교", campusId: 105, campusName: "바이오메디캠퍼스", fullCampusName: "동국대학교 바이오메디캠퍼스" },
  { institutionId: 72, institutionName: "동국대학교", campusId: 104, campusName: "WISE캠퍼스", fullCampusName: "동국대학교 WISE캠퍼스" },
  { institutionId: 73, institutionName: "동덕여자대학교", campusId: 107, campusName: "본교", fullCampusName: "동덕여자대학교" },
  { institutionId: 74, institutionName: "동명대학교", campusId: 108, campusName: "본교", fullCampusName: "동명대학교" },
  { institutionId: 75, institutionName: "동서대학교", campusId: 110, campusName: "주례캠퍼스", fullCampusName: "동서대학교 주례캠퍼스" },
  { institutionId: 75, institutionName: "동서대학교", campusId: 109, campusName: "센텀캠퍼스", fullCampusName: "동서대학교 센텀캠퍼스" },
  { institutionId: 76, institutionName: "동신대학교", campusId: 111, campusName: "본교", fullCampusName: "동신대학교" },
  { institutionId: 77, institutionName: "동아대학교", campusId: 113, campusName: "승학캠퍼스", fullCampusName: "동아대학교 승학캠퍼스" },
  { institutionId: 77, institutionName: "동아대학교", campusId: 112, campusName: "부민캠퍼스", fullCampusName: "동아대학교 부민캠퍼스" },
  { institutionId: 78, institutionName: "동양대학교", campusId: 115, campusName: "영주캠퍼스", fullCampusName: "동양대학교 영주캠퍼스" },
  { institutionId: 78, institutionName: "동양대학교", campusId: 114, campusName: "동두천캠퍼스", fullCampusName: "동양대학교 동두천캠퍼스" },
  { institutionId: 79, institutionName: "동의대학교", campusId: 116, campusName: "본교", fullCampusName: "동의대학교" },
  { institutionId: 80, institutionName: "디지털서울문화예술대학교", campusId: 117, campusName: "본교", fullCampusName: "디지털서울문화예술대학교" },
  { institutionId: 81, institutionName: "루터대학교", campusId: 118, campusName: "본교", fullCampusName: "루터대학교" },
  { institutionId: 82, institutionName: "명지대학교", campusId: 120, campusName: "자연캠퍼스", fullCampusName: "명지대학교 자연캠퍼스" },
  { institutionId: 82, institutionName: "명지대학교", campusId: 119, campusName: "인문캠퍼스", fullCampusName: "명지대학교 인문캠퍼스" },
  { institutionId: 83, institutionName: "목원대학교", campusId: 121, campusName: "본교", fullCampusName: "목원대학교" },
  { institutionId: 84, institutionName: "목포가톨릭대학교", campusId: 122, campusName: "본교", fullCampusName: "목포가톨릭대학교" },
  { institutionId: 85, institutionName: "배재대학교", campusId: 123, campusName: "본교", fullCampusName: "배재대학교" },
  { institutionId: 86, institutionName: "백석대학교", campusId: 124, campusName: "본교", fullCampusName: "백석대학교" },
  { institutionId: 87, institutionName: "부산가톨릭대학교", campusId: 125, campusName: "본교", fullCampusName: "부산가톨릭대학교" },
  { institutionId: 88, institutionName: "부산교육대학교", campusId: 126, campusName: "본교", fullCampusName: "부산교육대학교" },
  { institutionId: 89, institutionName: "부산대학교", campusId: 128, campusName: "부산캠퍼스", fullCampusName: "부산대학교 부산캠퍼스" },
  { institutionId: 89, institutionName: "부산대학교", campusId: 127, campusName: "밀양캠퍼스", fullCampusName: "부산대학교 밀양캠퍼스" },
  { institutionId: 89, institutionName: "부산대학교", campusId: 129, campusName: "양산캠퍼스", fullCampusName: "부산대학교 양산캠퍼스" },
  { institutionId: 90, institutionName: "부산디지털대학교", campusId: 130, campusName: "본교", fullCampusName: "부산디지털대학교" },
  { institutionId: 91, institutionName: "부산외국어대학교", campusId: 131, campusName: "본교", fullCampusName: "부산외국어대학교" },
  { institutionId: 92, institutionName: "부산장신대학교", campusId: 132, campusName: "본교", fullCampusName: "부산장신대학교" },
  { institutionId: 93, institutionName: "사이버한국외국어대학교", campusId: 133, campusName: "본교", fullCampusName: "사이버한국외국어대학교" },
  { institutionId: 94, institutionName: "삼성전자공과대학교", campusId: 134, campusName: "본교", fullCampusName: "삼성전자공과대학교" },
  { institutionId: 95, institutionName: "삼육대학교", campusId: 135, campusName: "본교", fullCampusName: "삼육대학교" },
  { institutionId: 96, institutionName: "상명대학교", campusId: 136, campusName: "서울캠퍼스", fullCampusName: "상명대학교 서울캠퍼스" },
  { institutionId: 96, institutionName: "상명대학교", campusId: 137, campusName: "천안캠퍼스", fullCampusName: "상명대학교 천안캠퍼스" },
  { institutionId: 97, institutionName: "상지대학교", campusId: 138, campusName: "본교", fullCampusName: "상지대학교" },
  { institutionId: 98, institutionName: "서강대학교", campusId: 139, campusName: "본교", fullCampusName: "서강대학교" },
  { institutionId: 99, institutionName: "서경대학교", campusId: 140, campusName: "본교", fullCampusName: "서경대학교" },
  { institutionId: 100, institutionName: "서울과학기술대학교", campusId: 141, campusName: "본교", fullCampusName: "서울과학기술대학교" },
  { institutionId: 101, institutionName: "서울교육대학교", campusId: 142, campusName: "본교", fullCampusName: "서울교육대학교" },
  { institutionId: 102, institutionName: "서울기독대학교", campusId: 143, campusName: "본교", fullCampusName: "서울기독대학교" },
  { institutionId: 103, institutionName: "서울대학교", campusId: 144, campusName: "관악캠퍼스", fullCampusName: "서울대학교 관악캠퍼스" },
  { institutionId: 103, institutionName: "서울대학교", campusId: 145, campusName: "연건캠퍼스", fullCampusName: "서울대학교 연건캠퍼스" },
  { institutionId: 104, institutionName: "서울디지털대학교", campusId: 146, campusName: "본교", fullCampusName: "서울디지털대학교" },
  { institutionId: 105, institutionName: "서울사이버대학교", campusId: 147, campusName: "본교", fullCampusName: "서울사이버대학교" },
  { institutionId: 106, institutionName: "서울시립대학교", campusId: 148, campusName: "본교", fullCampusName: "서울시립대학교" },
  { institutionId: 107, institutionName: "서울신학대학교", campusId: 149, campusName: "본교", fullCampusName: "서울신학대학교" },
  { institutionId: 108, institutionName: "서울여자대학교", campusId: 150, campusName: "본교", fullCampusName: "서울여자대학교" },
  { institutionId: 109, institutionName: "서울장신대학교", campusId: 151, campusName: "본교", fullCampusName: "서울장신대학교" },
  { institutionId: 110, institutionName: "서울한영대학교", campusId: 152, campusName: "본교", fullCampusName: "서울한영대학교" },
  { institutionId: 111, institutionName: "서원대학교", campusId: 153, campusName: "본교", fullCampusName: "서원대학교" },
  { institutionId: 112, institutionName: "선문대학교", campusId: 154, campusName: "본교", fullCampusName: "선문대학교" },
  { institutionId: 113, institutionName: "성결대학교", campusId: 155, campusName: "본교", fullCampusName: "성결대학교" },
  { institutionId: 114, institutionName: "성공회대학교", campusId: 156, campusName: "본교", fullCampusName: "성공회대학교" },
  { institutionId: 115, institutionName: "성균관대학교", campusId: 157, campusName: "인문사회과학캠퍼스", fullCampusName: "성균관대학교 인문사회과학캠퍼스" },
  { institutionId: 115, institutionName: "성균관대학교", campusId: 158, campusName: "자연과학캠퍼스", fullCampusName: "성균관대학교 자연과학캠퍼스" },
  { institutionId: 116, institutionName: "성신여자대학교", campusId: 159, campusName: "수정캠퍼스", fullCampusName: "성신여자대학교 수정캠퍼스" },
  { institutionId: 116, institutionName: "성신여자대학교", campusId: 160, campusName: "운정그린캠퍼스", fullCampusName: "성신여자대학교 운정그린캠퍼스" },
  { institutionId: 117, institutionName: "세명대학교", campusId: 161, campusName: "본교", fullCampusName: "세명대학교" },
  { institutionId: 118, institutionName: "세종대학교", campusId: 162, campusName: "본교", fullCampusName: "세종대학교" },
  { institutionId: 119, institutionName: "세종사이버대학교", campusId: 163, campusName: "본교", fullCampusName: "세종사이버대학교" },
  { institutionId: 120, institutionName: "세한대학교", campusId: 165, campusName: "영암캠퍼스", fullCampusName: "세한대학교 영암캠퍼스" },
  { institutionId: 120, institutionName: "세한대학교", campusId: 164, campusName: "당진캠퍼스", fullCampusName: "세한대학교 당진캠퍼스" },
  { institutionId: 121, institutionName: "송원대학교", campusId: 166, campusName: "본교", fullCampusName: "송원대학교" },
  { institutionId: 122, institutionName: "수원가톨릭대학교", campusId: 167, campusName: "본교", fullCampusName: "수원가톨릭대학교" },
  { institutionId: 123, institutionName: "수원대학교", campusId: 168, campusName: "본교", fullCampusName: "수원대학교" },
  { institutionId: 124, institutionName: "숙명여자대학교", campusId: 169, campusName: "본교", fullCampusName: "숙명여자대학교" },
  { institutionId: 125, institutionName: "순복음총회신학교", campusId: 170, campusName: "본교", fullCampusName: "순복음총회신학교" },
  { institutionId: 126, institutionName: "순천향대학교", campusId: 171, campusName: "제1캠퍼스", fullCampusName: "순천향대학교 제1캠퍼스" },
  { institutionId: 126, institutionName: "순천향대학교", campusId: 172, campusName: "제2캠퍼스", fullCampusName: "순천향대학교 제2캠퍼스" },
  { institutionId: 127, institutionName: "숭실대학교", campusId: 173, campusName: "본교", fullCampusName: "숭실대학교" },
  { institutionId: 128, institutionName: "숭실사이버대학교", campusId: 174, campusName: "본교", fullCampusName: "숭실사이버대학교" },
  { institutionId: 129, institutionName: "신경주대학교", campusId: 175, campusName: "본교", fullCampusName: "신경주대학교" },
  { institutionId: 130, institutionName: "신라대학교", campusId: 176, campusName: "본교", fullCampusName: "신라대학교" },
  { institutionId: 131, institutionName: "신한대학교", campusId: 178, campusName: "의정부캠퍼스", fullCampusName: "신한대학교 의정부캠퍼스" },
  { institutionId: 131, institutionName: "신한대학교", campusId: 177, campusName: "동두천캠퍼스", fullCampusName: "신한대학교 동두천캠퍼스" },
  { institutionId: 132, institutionName: "아신대학교", campusId: 179, campusName: "본교", fullCampusName: "아신대학교" },
  { institutionId: 133, institutionName: "아주대학교", campusId: 180, campusName: "본교", fullCampusName: "아주대학교" },
  { institutionId: 134, institutionName: "안양대학교", campusId: 182, campusName: "안양캠퍼스", fullCampusName: "안양대학교 안양캠퍼스" },
  { institutionId: 134, institutionName: "안양대학교", campusId: 181, campusName: "강화캠퍼스", fullCampusName: "안양대학교 강화캠퍼스" },
  { institutionId: 135, institutionName: "연세대학교", campusId: 185, campusName: "신촌캠퍼스", fullCampusName: "연세대학교 신촌캠퍼스" },
  { institutionId: 135, institutionName: "연세대학교", campusId: 183, campusName: "국제캠퍼스", fullCampusName: "연세대학교 국제캠퍼스" },
  { institutionId: 135, institutionName: "연세대학교", campusId: 184, campusName: "미래캠퍼스", fullCampusName: "연세대학교 미래캠퍼스" },
  { institutionId: 136, institutionName: "영남대학교", campusId: 186, campusName: "경산캠퍼스", fullCampusName: "영남대학교 경산캠퍼스" },
  { institutionId: 136, institutionName: "영남대학교", campusId: 187, campusName: "대명캠퍼스", fullCampusName: "영남대학교 대명캠퍼스" },
  { institutionId: 137, institutionName: "영남사이버대학교", campusId: 188, campusName: "본교", fullCampusName: "영남사이버대학교" },
  { institutionId: 138, institutionName: "영남신학대학교", campusId: 189, campusName: "본교", fullCampusName: "영남신학대학교" },
  { institutionId: 139, institutionName: "영산대학교", campusId: 190, campusName: "양산캠퍼스", fullCampusName: "영산대학교 양산캠퍼스" },
  { institutionId: 139, institutionName: "영산대학교", campusId: 191, campusName: "해운대캠퍼스", fullCampusName: "영산대학교 해운대캠퍼스" },
  { institutionId: 140, institutionName: "영산선학대학교", campusId: 192, campusName: "본교", fullCampusName: "영산선학대학교" },
  { institutionId: 141, institutionName: "예수대학교", campusId: 193, campusName: "본교", fullCampusName: "예수대학교" },
  { institutionId: 142, institutionName: "예원예술대학교", campusId: 195, campusName: "임실캠퍼스", fullCampusName: "예원예술대학교 임실캠퍼스" },
  { institutionId: 142, institutionName: "예원예술대학교", campusId: 194, campusName: "양주캠퍼스", fullCampusName: "예원예술대학교 양주캠퍼스" },
  { institutionId: 143, institutionName: "용인대학교", campusId: 196, campusName: "본교", fullCampusName: "용인대학교" },
  { institutionId: 144, institutionName: "우석대학교", campusId: 197, campusName: "전주캠퍼스", fullCampusName: "우석대학교 전주캠퍼스" },
  { institutionId: 144, institutionName: "우석대학교", campusId: 198, campusName: "진천캠퍼스", fullCampusName: "우석대학교 진천캠퍼스" },
  { institutionId: 145, institutionName: "우송대학교", campusId: 199, campusName: "본교", fullCampusName: "우송대학교" },
  { institutionId: 146, institutionName: "울산과학기술원", campusId: 200, campusName: "본교", fullCampusName: "울산과학기술원" },
  { institutionId: 147, institutionName: "울산대학교", campusId: 201, campusName: "본교", fullCampusName: "울산대학교" },
  { institutionId: 148, institutionName: "원광대학교", campusId: 203, campusName: "익산캠퍼스", fullCampusName: "원광대학교 익산캠퍼스" },
  { institutionId: 148, institutionName: "원광대학교", campusId: 202, campusName: "보건캠퍼스", fullCampusName: "원광대학교 보건캠퍼스" },
  { institutionId: 149, institutionName: "원광디지털대학교", campusId: 204, campusName: "본교", fullCampusName: "원광디지털대학교" },
  { institutionId: 150, institutionName: "위덕대학교", campusId: 205, campusName: "본교", fullCampusName: "위덕대학교" },
  { institutionId: 151, institutionName: "유원대학교", campusId: 207, campusName: "영동캠퍼스", fullCampusName: "유원대학교 영동캠퍼스" },
  { institutionId: 151, institutionName: "유원대학교", campusId: 206, campusName: "아산캠퍼스", fullCampusName: "유원대학교 아산캠퍼스" },
  { institutionId: 152, institutionName: "을지대학교", campusId: 208, campusName: "대전캠퍼스", fullCampusName: "을지대학교 대전캠퍼스" },
  { institutionId: 152, institutionName: "을지대학교", campusId: 209, campusName: "성남캠퍼스", fullCampusName: "을지대학교 성남캠퍼스" },
  { institutionId: 152, institutionName: "을지대학교", campusId: 210, campusName: "의정부캠퍼스", fullCampusName: "을지대학교 의정부캠퍼스" },
  { institutionId: 153, institutionName: "이화여자대학교", campusId: 211, campusName: "제1캠퍼스", fullCampusName: "이화여자대학교 제1캠퍼스" },
  { institutionId: 153, institutionName: "이화여자대학교", campusId: 212, campusName: "제2캠퍼스", fullCampusName: "이화여자대학교 제2캠퍼스" },
  { institutionId: 154, institutionName: "인제대학교", campusId: 213, campusName: "김해캠퍼스", fullCampusName: "인제대학교 김해캠퍼스" },
  { institutionId: 154, institutionName: "인제대학교", campusId: 214, campusName: "부산캠퍼스", fullCampusName: "인제대학교 부산캠퍼스" },
  { institutionId: 155, institutionName: "인천가톨릭대학교", campusId: 215, campusName: "강화캠퍼스", fullCampusName: "인천가톨릭대학교 강화캠퍼스" },
  { institutionId: 155, institutionName: "인천가톨릭대학교", campusId: 216, campusName: "송도국제캠퍼스", fullCampusName: "인천가톨릭대학교 송도국제캠퍼스" },
  { institutionId: 156, institutionName: "인천대학교", campusId: 217, campusName: "본교", fullCampusName: "인천대학교" },
  { institutionId: 157, institutionName: "인하대학교", campusId: 218, campusName: "본교", fullCampusName: "인하대학교" },
  { institutionId: 158, institutionName: "장로회신학대학교", campusId: 219, campusName: "본교", fullCampusName: "장로회신학대학교" },
  { institutionId: 159, institutionName: "전남대학교", campusId: 220, campusName: "광주캠퍼스", fullCampusName: "전남대학교 광주캠퍼스" },
  { institutionId: 159, institutionName: "전남대학교", campusId: 221, campusName: "여수캠퍼스", fullCampusName: "전남대학교 여수캠퍼스" },
  { institutionId: 160, institutionName: "전북대학교", campusId: 222, campusName: "전주캠퍼스", fullCampusName: "전북대학교 전주캠퍼스" },
  { institutionId: 160, institutionName: "전북대학교", campusId: 223, campusName: "특성화캠퍼스", fullCampusName: "전북대학교 특성화캠퍼스" },
  { institutionId: 161, institutionName: "전주교육대학교", campusId: 224, campusName: "본교", fullCampusName: "전주교육대학교" },
  { institutionId: 162, institutionName: "전주대학교", campusId: 225, campusName: "본교", fullCampusName: "전주대학교" },
  { institutionId: 163, institutionName: "정석대학", campusId: 226, campusName: "본교", fullCampusName: "정석대학" },
  { institutionId: 164, institutionName: "제주국제대학교", campusId: 227, campusName: "본교", fullCampusName: "제주국제대학교" },
  { institutionId: 165, institutionName: "제주대학교", campusId: 228, campusName: "본교", fullCampusName: "제주대학교" },
  { institutionId: 166, institutionName: "조선대학교", campusId: 229, campusName: "본교", fullCampusName: "조선대학교" },
  { institutionId: 167, institutionName: "중부대학교", campusId: 231, campusName: "충청국제캠퍼스", fullCampusName: "중부대학교 충청국제캠퍼스" },
  { institutionId: 167, institutionName: "중부대학교", campusId: 230, campusName: "고양창의캠퍼스", fullCampusName: "중부대학교 고양창의캠퍼스" },
  { institutionId: 168, institutionName: "중앙대학교", campusId: 233, campusName: "서울캠퍼스", fullCampusName: "중앙대학교 서울캠퍼스" },
  { institutionId: 168, institutionName: "중앙대학교", campusId: 232, campusName: "다빈치캠퍼스", fullCampusName: "중앙대학교 다빈치캠퍼스" },
  { institutionId: 169, institutionName: "중앙승가대학교", campusId: 234, campusName: "본교", fullCampusName: "중앙승가대학교" },
  { institutionId: 170, institutionName: "중원대학교", campusId: 235, campusName: "본교", fullCampusName: "중원대학교" },
  { institutionId: 171, institutionName: "진주교육대학교", campusId: 236, campusName: "본교", fullCampusName: "진주교육대학교" },
  { institutionId: 172, institutionName: "차의과학대학교", campusId: 237, campusName: "본교", fullCampusName: "차의과학대학교" },
  { institutionId: 173, institutionName: "창신대학교", campusId: 238, campusName: "본교", fullCampusName: "창신대학교" },
  { institutionId: 174, institutionName: "청운대학교", campusId: 240, campusName: "홍성캠퍼스", fullCampusName: "청운대학교 홍성캠퍼스" },
  { institutionId: 174, institutionName: "청운대학교", campusId: 239, campusName: "인천캠퍼스", fullCampusName: "청운대학교 인천캠퍼스" },
  { institutionId: 175, institutionName: "청주교육대학교", campusId: 241, campusName: "본교", fullCampusName: "청주교육대학교" },
  { institutionId: 176, institutionName: "청주대학교", campusId: 242, campusName: "제1캠퍼스", fullCampusName: "청주대학교 제1캠퍼스" },
  { institutionId: 176, institutionName: "청주대학교", campusId: 243, campusName: "제2캠퍼스", fullCampusName: "청주대학교 제2캠퍼스" },
  { institutionId: 177, institutionName: "초당대학교", campusId: 244, campusName: "본교", fullCampusName: "초당대학교" },
  { institutionId: 178, institutionName: "총신대학교", campusId: 245, campusName: "본교", fullCampusName: "총신대학교" },
  { institutionId: 179, institutionName: "추계예술대학교", campusId: 246, campusName: "본교", fullCampusName: "추계예술대학교" },
  { institutionId: 180, institutionName: "춘천교육대학교", campusId: 247, campusName: "본교", fullCampusName: "춘천교육대학교" },
  { institutionId: 181, institutionName: "충남대학교", campusId: 248, campusName: "본교", fullCampusName: "충남대학교" },
  { institutionId: 182, institutionName: "충북대학교", campusId: 249, campusName: "본교", fullCampusName: "충북대학교" },
  { institutionId: 183, institutionName: "칼빈대학교", campusId: 250, campusName: "본교", fullCampusName: "칼빈대학교" },
  { institutionId: 184, institutionName: "태재대학교", campusId: 251, campusName: "본교", fullCampusName: "태재대학교" },
  { institutionId: 185, institutionName: "평택대학교", campusId: 252, campusName: "본교", fullCampusName: "평택대학교" },
  { institutionId: 186, institutionName: "포항공과대학교", campusId: 253, campusName: "본교", fullCampusName: "포항공과대학교" },
  { institutionId: 187, institutionName: "한경국립대학교", campusId: 254, campusName: "안성캠퍼스", fullCampusName: "한경국립대학교 안성캠퍼스" },
  { institutionId: 187, institutionName: "한경국립대학교", campusId: 255, campusName: "평택캠퍼스", fullCampusName: "한경국립대학교 평택캠퍼스" },
  { institutionId: 188, institutionName: "한국공학대학교", campusId: 256, campusName: "본교", fullCampusName: "한국공학대학교" },
  { institutionId: 189, institutionName: "한국과학기술원", campusId: 257, campusName: "본교", fullCampusName: "한국과학기술원" },
  { institutionId: 190, institutionName: "한국교원대학교", campusId: 258, campusName: "본교", fullCampusName: "한국교원대학교" },
  { institutionId: 191, institutionName: "한국기술교육대학교", campusId: 259, campusName: "본교", fullCampusName: "한국기술교육대학교" },
  { institutionId: 192, institutionName: "한국방송통신대학교", campusId: 260, campusName: "본교", fullCampusName: "한국방송통신대학교" },
  { institutionId: 193, institutionName: "한국성서대학교", campusId: 261, campusName: "본교", fullCampusName: "한국성서대학교" },
  { institutionId: 194, institutionName: "한국에너지공과대학교", campusId: 262, campusName: "본교", fullCampusName: "한국에너지공과대학교" },
  { institutionId: 195, institutionName: "한국열린사이버대학교", campusId: 263, campusName: "본교", fullCampusName: "한국열린사이버대학교" },
  { institutionId: 196, institutionName: "한국예술종합학교", campusId: 265, campusName: "석관동캠퍼스", fullCampusName: "한국예술종합학교 석관동캠퍼스" },
  { institutionId: 196, institutionName: "한국예술종합학교", campusId: 264, campusName: "서초동캠퍼스", fullCampusName: "한국예술종합학교 서초동캠퍼스" },
  { institutionId: 197, institutionName: "한국외국어대학교", campusId: 267, campusName: "서울캠퍼스", fullCampusName: "한국외국어대학교 서울캠퍼스" },
  { institutionId: 197, institutionName: "한국외국어대학교", campusId: 266, campusName: "글로벌캠퍼스", fullCampusName: "한국외국어대학교 글로벌캠퍼스" },
  { institutionId: 198, institutionName: "한국전통문화대학교", campusId: 268, campusName: "본교", fullCampusName: "한국전통문화대학교" },
  { institutionId: 199, institutionName: "한국체육대학교", campusId: 269, campusName: "본교", fullCampusName: "한국체육대학교" },
  { institutionId: 200, institutionName: "한국침례신학대학교", campusId: 270, campusName: "본교", fullCampusName: "한국침례신학대학교" },
  { institutionId: 201, institutionName: "한국항공대학교", campusId: 271, campusName: "본교", fullCampusName: "한국항공대학교" },
  { institutionId: 202, institutionName: "한남대학교", campusId: 273, campusName: "오정캠퍼스", fullCampusName: "한남대학교 오정캠퍼스" },
  { institutionId: 202, institutionName: "한남대학교", campusId: 272, campusName: "대덕캠퍼스", fullCampusName: "한남대학교 대덕캠퍼스" },
  { institutionId: 203, institutionName: "한동대학교", campusId: 274, campusName: "본교", fullCampusName: "한동대학교" },
  { institutionId: 204, institutionName: "한라대학교", campusId: 275, campusName: "본교", fullCampusName: "한라대학교" },
  { institutionId: 205, institutionName: "한림대학교", campusId: 276, campusName: "본교", fullCampusName: "한림대학교" },
  { institutionId: 206, institutionName: "한서대학교", campusId: 277, campusName: "서산캠퍼스", fullCampusName: "한서대학교 서산캠퍼스" },
  { institutionId: 206, institutionName: "한서대학교", campusId: 278, campusName: "태안캠퍼스", fullCampusName: "한서대학교 태안캠퍼스" },
  { institutionId: 207, institutionName: "한성대학교", campusId: 279, campusName: "본교", fullCampusName: "한성대학교" },
  { institutionId: 208, institutionName: "한세대학교", campusId: 280, campusName: "본교", fullCampusName: "한세대학교" },
  { institutionId: 209, institutionName: "한신대학교", campusId: 281, campusName: "본교", fullCampusName: "한신대학교" },
  { institutionId: 210, institutionName: "한양대학교", campusId: 283, campusName: "서울캠퍼스", fullCampusName: "한양대학교 서울캠퍼스" },
  { institutionId: 210, institutionName: "한양대학교", campusId: 282, campusName: "ERICA캠퍼스", fullCampusName: "한양대학교 ERICA캠퍼스" },
  { institutionId: 211, institutionName: "한양사이버대학교", campusId: 284, campusName: "본교", fullCampusName: "한양사이버대학교" },
  { institutionId: 212, institutionName: "한일장신대학교", campusId: 285, campusName: "본교", fullCampusName: "한일장신대학교" },
  { institutionId: 213, institutionName: "협성대학교", campusId: 286, campusName: "본교", fullCampusName: "협성대학교" },
  { institutionId: 214, institutionName: "호남대학교", campusId: 287, campusName: "본교", fullCampusName: "호남대학교" },
  { institutionId: 215, institutionName: "호남신학대학교", campusId: 288, campusName: "본교", fullCampusName: "호남신학대학교" },
  { institutionId: 216, institutionName: "호서대학교", campusId: 290, campusName: "아산캠퍼스", fullCampusName: "호서대학교 아산캠퍼스" },
  { institutionId: 216, institutionName: "호서대학교", campusId: 291, campusName: "천안캠퍼스", fullCampusName: "호서대학교 천안캠퍼스" },
  { institutionId: 216, institutionName: "호서대학교", campusId: 289, campusName: "산학융합캠퍼스", fullCampusName: "호서대학교 산학융합캠퍼스" },
  { institutionId: 217, institutionName: "호원대학교", campusId: 292, campusName: "본교", fullCampusName: "호원대학교" },
  { institutionId: 218, institutionName: "홍익대학교", campusId: 293, campusName: "서울캠퍼스", fullCampusName: "홍익대학교 서울캠퍼스" },
  { institutionId: 218, institutionName: "홍익대학교", campusId: 294, campusName: "세종캠퍼스", fullCampusName: "홍익대학교 세종캠퍼스" },
  { institutionId: 219, institutionName: "화성의과학대학교", campusId: 295, campusName: "본교", fullCampusName: "화성의과학대학교" },
  { institutionId: 220, institutionName: "화신사이버대학교", campusId: 296, campusName: "본교", fullCampusName: "화신사이버대학교" },
];

export const findCampusMappingById = (campusId: number) =>
  INSTITUTION_CAMPUS_MAPPINGS.find((item) => item.campusId === campusId);

export const findInstitutionMappingsByName = (institutionName: string) =>
  INSTITUTION_CAMPUS_MAPPINGS.filter((item) => item.institutionName === institutionName);

const normalizeSearchText = (value: string) =>
  value.toLocaleLowerCase().replace(/\s+/g, "");

export const findInstitutionCampusMappingByFullName = (fullCampusName: string) => {
  const normalizedFullCampusName = normalizeSearchText(fullCampusName.trim());
  if (!normalizedFullCampusName) return undefined;

  return INSTITUTION_CAMPUS_MAPPINGS.find(
    (item) => normalizeSearchText(item.fullCampusName) === normalizedFullCampusName
  );
};

export const searchInstitutionCampusMappings = (query: string, limit = 10) => {
  const normalizedQuery = normalizeSearchText(query.trim());
  if (!normalizedQuery) return [];

  return INSTITUTION_CAMPUS_MAPPINGS
    .filter((item) => normalizeSearchText(item.fullCampusName).includes(normalizedQuery))
    .slice(0, limit);
};

export const formatEducationSchoolName = (
  institutionName: string,
  campusName?: string | null,
  campusId?: number | null,
) => {
  if (campusId) {
    const mapping = findCampusMappingById(campusId);
    if (mapping) return mapping.fullCampusName;
  }

  if (!campusName || campusName === "본교") return institutionName;
  return `${institutionName} ${campusName}`;
};
